import { flatDataKeyConstants } from "./FlatDataKeyConstants";
// flat class? easier to give as prop and store in DB
const keyConst = flatDataKeyConstants;
export const exampleFlatData: { [key: string]: { [key: string]: string } } = {
  "153089151": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153089151",
    [keyConst.adress]: "Lenbachstr. 34, Holsterhausen",
    [keyConst.title]:
      "Helle und geräumige 3-Zimmer-Wohnung in ruhiger Wohngegend",
    [keyConst.rent]: "522 + heizen",
    [keyConst.distanceUKE]: "550m",
    [keyConst.timeUKE]: "",
    [keyConst.distanceTrain]: "500m",
    [keyConst.email]: "",
    [keyConst.telephone]: "0209 9848000",
    [keyConst.key]: "153089151",
  },
  "152116443": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/152116443",
    [keyConst.adress]: "Keplerstraße 108, Holsterhausen",
    [keyConst.title]:
      "Schöne 3-Zimmer Wohnung in zentraler Lage! Gute Anbindung zur Innenstadt!",
    [keyConst.rent]: "620 + heizen",
    [keyConst.distanceUKE]: "1200m",
    [keyConst.timeUKE]: "",
    [keyConst.distanceTrain]: "200m",
    [keyConst.email]: "beck@hausverwaltung-schmidt.de",
    [keyConst.telephone]: "+49 201 86227-18 ",
    [keyConst.key]: "152116443",
  },
  "104062381": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/104062381",
    [keyConst.adress]: "Holsterhauser Str. 45, Holsterhausen",
    [keyConst.title]: "gut geschnittene 3-Zimmer Wohnung am Gemarkenplatz",
    [keyConst.rent]: "540",
    [keyConst.distanceUKE]: "1000m",
    [keyConst.timeUKE]: "",
    [keyConst.distanceTrain]: "50m",
    [keyConst.notes]: "[Formular 23.09.]",
    [keyConst.email]: "info@jhb-immobilien.de",
    [keyConst.telephone]: "",
    [keyConst.key]: "152116443",
  },
  // "153599880": {
  //   [keyConst.link]:
  //     "https://www.immobilienscout24.de/expose/153599880",
  //   [keyConst.adress]: "Holsterhausen",
  //   [keyConst.title]: "Ruhige Altbauwohnung in Essen Holsterhausen",
  //   [keyConst.rent]: "615 + heizen",
  //   [keyConst.distanceUKE]: "",
  //   [keyConst.timeUKE]: "",
  //   [keyConst.distanceTrain]: "",
  //   [keyConst.notes]: "",
  //   [keyConst.email]: "",
  //   [keyConst.telephone]: "",
  //   [keyConst.key]: "153599880",
  // },
  "151663170": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/151663170",
    [keyConst.adress]: "Stephensonstr. 6, Frohnhausen",
    [keyConst.title]:
      "Sehr schöne, helle und gemütliche 3,5 Raum-Wohnung mit großem Balkon",
    [keyConst.rent]: "685 + heizen",
    [keyConst.distanceUKE]: "1800m",
    [keyConst.timeUKE]: "15 min",
    [keyConst.distanceTrain]: "1000m Essen West",
    [keyConst.notes]: "",
    [keyConst.email]: "info@immobesta.de",
    [keyConst.telephone]: "0209 37780025",
    [keyConst.key]: "151663170",
  },
  // "153187343": {
  //   [keyConst.link]:
  //     "https://www.immobilienscout24.de/expose/153187343",
  //   [keyConst.adress]: "Aachener Str. 2, Frohnhausen",
  //   [keyConst.title]: "Attraktive 3-Zimmer-Wohnung mit Balkon!",
  //   [keyConst.rent]: "660 + heizen",
  //   [keyConst.distanceUKE]: "1800m",
  //   [keyConst.timeUKE]: "15 min",
  //   [keyConst.distanceTrain]: "500m",
  //   [keyConst.notes]: "",
  //   [keyConst.email]: "",
  //   [keyConst.telephone]: "",
  //   [keyConst.key]: "153187343",
  // },
  "133018653": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/133018653",
    [keyConst.adress]: "Amixstraße 4, Altendorf",
    [keyConst.title]:
      "Schöne moderne 3-Zimmer-Wohnung mit moderner Einbauküche und Bad",
    [keyConst.rent]: "630 + heizen",
    [keyConst.distanceUKE]: "3500m",
    [keyConst.timeUKE]: "18 bis 30 min",
    [keyConst.distanceTrain]: "500m",
    [keyConst.notes]: "Mieter+ Guido",
    [keyConst.email]: "",
    [keyConst.telephone]: "",
    [keyConst.key]: "133018653",
  },
  "153560957": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153560957",
    [keyConst.adress]: "Besselstr ",
    [keyConst.title]:
      "Modernisierte 3,5-Zimmer-DG-Wohnung mit Klimaanlage und EBK",
    [keyConst.rent]: "745",
    [keyConst.distanceUKE]: "2900m",
    [keyConst.timeUKE]: "",
    [keyConst.distanceTrain]: "",
    [keyConst.notes]: "Mieter+ Guido",
    [keyConst.email]: "",
    [keyConst.telephone]: "",
    [keyConst.key]: "153560957",
  },
  "151955211": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/151955211",
    [keyConst.adress]: "Nobermanns Hude 11, Altenessen-Süd",
    [keyConst.title]: "Renovierte 3 Zimmer-Wohnung",
    [keyConst.rent]: "585 + heizen",
    [keyConst.distanceUKE]: "5900m",
    [keyConst.timeUKE]: "25 min",
    [keyConst.distanceTrain]: "300m",
    [keyConst.notes]: "",
    [keyConst.email]: "nfo@coreimmobilien.com",
    [keyConst.telephone]: "",
    [keyConst.key]: "151955211",
  },
  // "153093234": {
  //   [keyConst.link]:
  //     "https://www.immobilienscout24.de/expose/153093234",
  //   [keyConst.adress]: "Kämpenstraße 27, Holsterhausen",
  //   [keyConst.title]:
  //     '"Schöne & zentral gelegene" 3-Zimmerwohnung - in Essen/Holsterhausen',
  //   [keyConst.rent]: "668,65",
  //   [keyConst.distanceUKE]: "1300m",
  //   [keyConst.timeUKE]: "",
  //   [keyConst.distanceTrain]: "300m",
  //   [keyConst.notes]:
  //     "Adresse unklar: 27 in Holsterhausen gibt es nicht glaube ich",
  //   [keyConst.email]: "",
  //   [keyConst.telephone]: "",
  //   [keyConst.key]: "153093234",
  // },
  "153208199": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153208199",
    [keyConst.adress]: "Kölner Straße 3, Frohnhausen",
    [keyConst.title]: "***Tolle Wohnung mit Terrasse sucht Mieter***",
    [keyConst.rent]: "605",
    [keyConst.distanceUKE]: "1800m",
    [keyConst.timeUKE]: "13 min",
    [keyConst.distanceTrain]: "70m Bus, 900m Essen West, 400m 106, 700m U18",
    [keyConst.notes]: "",
    [keyConst.email]: "info@s-c-immobilien.de",
    [keyConst.telephone]: "0231 58690631",
    [keyConst.key]: "153208199",
  },
  // "129146944": {
  //   [keyConst.link]:
  //     "https://www.immobilienscout24.de/expose/129146944",
  //   [keyConst.adress]: "Dinglerstr. 6, Holsterhausen",
  //   [keyConst.title]:
  //     "Stadtnah, hell & ruhig - moderne 2,5-Raum-Whg mit voll ausgestatteter Küche",
  //   [keyConst.rent]: "750",
  //   [keyConst.distanceUKE]: "2000m",
  //   [keyConst.timeUKE]: "12 min",
  //   [keyConst.distanceTrain]: "200m Bus, 900m Essen West",
  //   [keyConst.notes]: "Privatanbieter, Küche",
  //   [keyConst.email]: "",
  //   [keyConst.telephone]: "",
  //   [keyConst.key]: "129146944",
  // },
  // "127641010": {
  //   [keyConst.link]:
  //     "https://www.immobilienscout24.de/expose/127641010",
  //   [keyConst.adress]: "Schweriner Str. 18, Frohnhausen",
  //   [keyConst.title]:
  //     "Ansprechende 3,5-Zimmer-Wohnung, EG, Balkon, Wannenbad",
  //   [keyConst.rent]: "635 + heizen",
  //   [keyConst.distanceUKE]: "2100m",
  //   [keyConst.timeUKE]: "",
  //   [keyConst.distanceTrain]: "400m",
  //   [keyConst.notes]: "",
  //   [keyConst.email]: "",
  //   [keyConst.telephone]: "",
  //   [keyConst.key]: "127641010",
  // },
  "153644854": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153644854",
    [keyConst.adress]: "Ruhrallee 34, Huttrop",
    [keyConst.title]: "Mein Zuhause in Essen",
    [keyConst.rent]: "697 + heizen",
    [keyConst.distanceUKE]: "2100m",
    [keyConst.timeUKE]: "25 min",
    [keyConst.distanceTrain]: "Bus 90m, 800m 109",
    [keyConst.notes]: "",
    [keyConst.email]: "info@allbau.de",
    [keyConst.telephone]: "0201 2207555",
    [keyConst.key]: "153644854",
  },
  "149925982": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/149925982",
    [keyConst.adress]: "Gemarkenstraße 70, Holsterhausen",
    [keyConst.title]:
      "DG-Wohnung in Essen-Holsterhausen PROVISIONFREI zu vermieten!",
    [keyConst.rent]: "610 + heizen",
    [keyConst.distanceUKE]: "850m",
    [keyConst.timeUKE]: "10 min",
    [keyConst.distanceTrain]: "300m",
    [keyConst.notes]: "Trotz Nummer über Kontaktformular",
    [keyConst.email]: "",
    [keyConst.telephone]: "0201 2805065",
    [keyConst.key]: "149925982",
  },
  "153813527": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153813527",
    [keyConst.adress]: "Reginenstraße 65, Rüttenscheid",
    [keyConst.title]: "Live smart!",
    [keyConst.rent]: "700 + heizen",
    [keyConst.distanceUKE]: "1600m",
    [keyConst.timeUKE]: "17 min",
    [keyConst.distanceTrain]: "400m, Bus 100m",
    [keyConst.notes]: "[Formular 23.09.] getrenntes WC, schrägen im Bad",
    [keyConst.email]: "",
    [keyConst.telephone]: "0201 8090388",
    [keyConst.key]: "153813527",
  },
  "152817468": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/152817468",
    [keyConst.adress]: "Alexanderstr. 47, Rüttenscheid",
    [keyConst.title]: "Rüttenscheid! DG-Wohnung in angenehmer Lage",
    [keyConst.rent]: "564 + heizen",
    [keyConst.distanceUKE]: "950m",
    [keyConst.timeUKE]: "15 min",
    [keyConst.distanceTrain]: "350m",
    [keyConst.notes]: "[Formular 23.09.] Kleine Küche",
    [keyConst.email]: "",
    [keyConst.telephone]: "",
    [keyConst.key]: "152817468",
  },
  "153088312": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153088312",
    [keyConst.adress]: "Hans-Thoma-Str. 43, Holsterhausen",
    [keyConst.title]: "Helle und geräumige 3-Zimmer-Wohnung mit Balkon",
    [keyConst.rent]: "592,75 + heizen",
    [keyConst.distanceUKE]: "600m",
    [keyConst.timeUKE]: "",
    [keyConst.distanceTrain]: "600m",
    [keyConst.notes]: "[Formular 23.09.] Balkon",
    [keyConst.email]: "",
    [keyConst.telephone]: "0209 9848000",
    [keyConst.key]: "153088312",
  },
  "151902046": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/151902046",
    [keyConst.adress]: "Tholstr. 10, Altendorf",
    [keyConst.title]:
      "3-Zimmer Wohnung | Gartenmitbenutzung | WG-Geeignet | 55 m²",
    [keyConst.rent]: "638",
    [keyConst.distanceUKE]: "3600m",
    [keyConst.timeUKE]: "25 min",
    [keyConst.distanceTrain]: "350m",
    [keyConst.notes]: "[Formular 23.09.]",
    [keyConst.email]: "",
    [keyConst.telephone]: "02236 9664044",
    [keyConst.key]: "151902046",
  },
  "151268039": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/151268039",
    [keyConst.adress]: "Steinmetzstraße 23-29, Südostviertel",
    [keyConst.title]: "Helle 3-Zi-Wohn-Oase im DG // Superlage mit Garten",
    [keyConst.rent]: "575",
    [keyConst.distanceUKE]: "3800m",
    [keyConst.timeUKE]: "27 min",
    [keyConst.distanceTrain]: "200m, Essen HBf 1200m",
    [keyConst.notes]: "[Formular 23.09.] Alte Bilder",
    [keyConst.email]: "",
    [keyConst.telephone]: "0176 36336374 (nach 18h)",
    [keyConst.key]: "151268039",
  },
  "153718413": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153718413",
    [keyConst.adress]: "Eulerstr. 25, Altendorf",
    [keyConst.title]:
      "Schöne, helle, 3,5 Zimmer-Wohnung im 3.OG, mit Gemeinschaftsgarten! Eulerstr. 25, E-West",
    [keyConst.rent]: "560",
    [keyConst.distanceUKE]: "2800m",
    [keyConst.timeUKE]: "18 min",
    [keyConst.distanceTrain]: "300m, Essen West 700m",
    [keyConst.notes]: "[Formular 23.09.] Weirder Schnitt, Wohnzimmer weit weg",
    [keyConst.email]: "",
    [keyConst.telephone]: "",
    [keyConst.key]: "153718413",
  },
  "152813924": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/152813924",
    [keyConst.adress]: "Unterdorfstraße 49, Altendorf,",
    [keyConst.title]: "Moderne 3-Zimmer Dachgeschosswohnung in ruhiger Lage",
    [keyConst.rent]: "618 + heizen",
    [keyConst.distanceUKE]: "2700m",
    [keyConst.timeUKE]: "15 min",
    [keyConst.distanceTrain]: "250m, Essen West 500m",
    [keyConst.notes]: "[Formular 23.09.], mit Küche",
    [keyConst.email]: "",
    [keyConst.telephone]: "02236 9664044",
    [keyConst.key]: "152813924",
  },
  "153753113": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153753113",
    [keyConst.adress]: "Duisburger Straße 2, Frohnhausen",
    [keyConst.title]:
      "Essen | Frisch sanierte 3-Raum-Wohnung mit Einbauküche und modernem Tageslichtbad",
    [keyConst.rent]: "694 + heizen",
    [keyConst.distanceUKE]: "2300m",
    [keyConst.timeUKE]: "20 min",
    [keyConst.distanceTrain]: "300m Bus",
    [keyConst.notes]: "[Formular 23.09.] Frisch saniert, Emily mag Küche nicht",
    [keyConst.email]: "",
    [keyConst.telephone]: "",
    [keyConst.key]: "153753113",
  },
  "153724707": {
    [keyConst.link]: "https://www.immobilienscout24.de/expose/153724707",
    [keyConst.adress]: "Postreitweg 1, Frohnhausen",
    [keyConst.title]:
      "Blick ins Grüne - 3 Raum-Wohnung in Frohnhausen zu vermieten",
    [keyConst.rent]: "660",
    [keyConst.distanceUKE]: "2100m",
    [keyConst.timeUKE]: "15 min",
    [keyConst.distanceTrain]: "500m",
    [keyConst.notes]: "[Formular 23.09.] riesige Küchenzeile",
    [keyConst.email]: "",
    [keyConst.telephone]: "0201 45881555",
    [keyConst.key]: "153724707",
  },
  // "key": {
  //   [keyConst.link]: "",
  //   [keyConst.adress]: "",
  //   [keyConst.title]: "",
  //   [keyConst.rent]: "",
  //   [keyConst.distanceUKE]: "",
  //   [keyConst.timeUKE]: "",
  //   [keyConst.distanceTrain]: "",
  //   [keyConst.notes]: "[Formular 23.09.]",
  //   [keyConst.email]: "",
  //   [keyConst.telephone]: "",
  //   [keyConst.key]: "",
  // },
};
